// ==UserScript==
// @ScriptName        自定义VIP
// @Author            @nobody
// @Function          
// @AddRequest        
// @WechatID          nobody
// @TgChannel         
// @Contribute        
// @UpdateTime        2026-03-05
// @Suitable          自行观看“# > ”注释内容
// @Attention         
// @Attention         
// @Version           V1.0.11
// @ScriptURL         
// ==/UserScript==



hostname = api.ventusky.com

# > ventusky vip
^https:\/\/(?:api|users)\.ventusky\.com\/(?:v2\/api\.premium|api\/api\.sync_user)\.php$ url script-response-body https://raw.githubusercontent.com/ddgksf2013/Scripts/refs/heads/master/amdc.js